### ISSUE TITLE
"agent not found"

### ISSUE THREAD

**Issue by CapoD** [xavidop/dialogflow-cx-cli#16]
### What happened?

We were trying to use the agent cli options (export/import/delete). Unfortunately, we always get the Error: ".....agent not found".

Would you confirm that the cli is working? If so, is there a way to enable debugging on the tool?

### How can we reproduce this?

Just export an agent.

### cxcli version

```bash
INFO[2023-01-16T17:07:05+01:00] Current version: 1.12.1
INFO[2023-01-16T17:07:05+01:00] You have installed the latest version!
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xavidop** [comment]
Hi @CapoD !

Thanks for using the tool! I just checked and the tool works fine.

Do you have the cloud configured on your laptop? if so, does the currently active project set to where your agent is located?

You can create a Service Account and a JSON key and pass it to the `cxcli` using the --credentials parameters:
```sh
cxcli agent export test-agent --project-id test-cx-346408 --location-id us-central1 --credentials credentials.json
```

You can check the authentications options [here](https://cxcli.xavidop.me/overview/authentication/)

**Comment by CapoD** [comment]
Hi @xavidop,

thanks for your quick reply. It seems to work by supplying service account credentials via the respective parameter.

So I believe that using the application default credentials does not work. However, I believe that the shown error is misleading since it does not convey an authentication problem which this should be. What do you think?

**Comment by xavidop** [comment]
You are completely right!

I want to re-think the error logs a bit. Also, I want to introduce tasks related to flows, webhooks, versions and environments!

I will close this issue since it was resolved!

Thanks for the feedback and thanks for using it!
