### ISSUE TITLE
Not able to find the latest version in https://hub.docker.com/r/xavidop/cxcli/tags

### ISSUE THREAD

**Issue by lavu1911** [xavidop/dialogflow-cx-cli#38]
### What happened?

The previous versions stopped working since the v1.29.0 has been pushed.  

Error:

time="2023-03-09T20:18:40Z" level=warning msg="A new version is available: 1.29.0. Please update the tool using your package manager or downloading the latest release from Github: https://github.com/xavidop/dialogflow-cx-cli/releases/latest"
time="2023-03-09T20:18:40Z" level=error msg="agent not found"

### How can we reproduce this?

docker pull xavidop/cxcli:v1.29.0

### cxcli version

```bash
v1.27.1
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Please push the latest version to docker hub or allow to use the previous versions.

**Comment by xavidop** [comment]
Thanks for reporting this! it should be good now!

**Comment by lavu1911** [comment]
thank u for quick response.  Appreciate it
