### ISSUE TITLE
Discord Link on Github and Official Pages Does Not Work

### ISSUE THREAD

**Issue by inayet** [xavidop/dialogflow-cx-cli#4]
### What happened?

Hi, 

Your discord link found on the readme doc and your hosted docs results in an invalid invitation. 

Thank you,
Inayet

### How can we reproduce this?

Click on the discord link

### cxcli version

```bash
NA
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xavidop** [comment]
should be good now! thanks for reporting it!
