### ISSUE TITLE
Links in Docs See Also Leading to 404

### ISSUE THREAD

**Issue by inayet** [xavidop/dialogflow-cx-cli#54]
### What happened?

While clicking on the links in See Also section led to 404 error, I tried a few other pages and similar event happened ending in a 404. 

### How can we reproduce this?

https://github.com/xavidop/dialogflow-cx-cli/blob/v1.41.0/docs/docs/cmd/cxcli.md
Click on the first or second link under the See Also section. 

### cxcli version

```bash
v1.41.0
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Hi @xavidop , excellent job on furthering the development CXCLI  👍

**Comment by xavidop** [comment]
@inayet should be good now!

**Comment by inayet** [comment]
@xavidop excellent
