### ISSUE TITLE
Error: tcp lookup no such host - when no location specified

### ISSUE THREAD

**Issue by koverholt** [xavidop/dialogflow-cx-cli#58]
### What happened?

When I run the following command to create an agent:

```
$ cxcli agent create TesterBot --credentials ~/.config/gcloud/service-account-key.json
```

It returns the following error:

```
ERRO[2023-04-18T21:20:07-05:00] Post "https://-dialogflow.googleapis.com:443/v3beta1/projects//locations//agents?%!a(MISSING)lt=json%!B(MISSING)enum-encoding%!D(MISSING)int": dial tcp: lookup -dialogflow.googleapis.com: no such host
```

### How can we reproduce this?

1. Install `cxcli`
2. Create a service account and a JSON key
3. Create an agent with `cxcli agent create [name] --credentials [path-to-json-key]`

### cxcli version

```bash
INFO[2023-04-18T21:22:18-05:00] Current version: 1.43.1
INFO[2023-04-18T21:22:19-05:00] You have installed the latest version!
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Does `cxcli` pull a default location from the `gcloud` config? If not, then the `--location-id` should be a required parameter.

Also, you might want to catch errors when `cxcli` tries to reach out to `https://-dialogflow.googleapis.com` (when the location is not specified) and/or allow users to use the `https://dialogflow.googleapis.com` service endpoint. Otherwise users might get confused by the tcp error and not know to specify a location.

Finally, thanks for the great tool! 😎

**Comment by koverholt** [comment]
As a related note, if the region is not specified, should `cxcli` default to the `global` region similar to the Dialogflow CX API?

https://cloud.google.com/dialogflow/cx/docs/concept/region

**Comment by xavidop** [comment]
> As a related note, if the region is not specified, should `cxcli` default to the `global` region similar to the Dialogflow CX API?
> 
> https://cloud.google.com/dialogflow/cx/docs/concept/region

that is a great idea @koverholt ! we can use `global` as the default one

**Comment by xavidop** [comment]
I am gonna close this issue in favour of this one: https://github.com/xavidop/dialogflow-cx-cli/issues/59 since the issue under the hood is the same: don't specify the required flags

**Comment by koverholt** [comment]
Sounds good to me, I'll add some more specific bullet points and proposed solutions to #59 rather than duping in this issue.
