### ISSUE TITLE
Minimal set of parameters should be required for agent create

### ISSUE THREAD

**Issue by koverholt** [xavidop/dialogflow-cx-cli#59]
### What happened?

I ran the following command:

```
$ cxcli agent create TesterBot -l us-central1 --credentials ~/.config/gcloud/service-account-key.json
```

and got an error about IAM permissions:

```
ERRO[2023-04-18T21:29:01-05:00] googleapi: Error 403: IAM permission 'dialogflow.agents.create' on 'projects//locations/us-central1' denied.
```

Through trial-and-error, I was able to determine that the location ID, project ID, default locale, and default timezone are required parameters, but the CLI does not enforce this. The working command and set of options was:

```
$ cxcli agent create TesterBot -e en -t America/Chicago -l us-central1 -p [project-id] --credentials ~/.config/gcloud/service-account-key.json
```

### How can we reproduce this?

1. Install `cxcli`
2. Create a service account and key
3. Run the command to create an agent with only the location ID and credentials options

### cxcli version

```bash
INFO[2023-04-18T21:34:52-05:00] Current version: 1.43.1
INFO[2023-04-18T21:34:52-05:00] You have installed the latest version!
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Proposed changes

- Require certain parameters in CLI (e.g., `location`, `locale`, `timezone` and others in `cxcli agent create`
- Block the command from running until required parameters are provided
- Can start with required params for `cxcli agent create`, but I imagine this will also apply to other subcommands
- Use smart defaults when possible to minimize friction for developer onboarding, for example:
  - Default to creating the agent in the `global` region when a location is not specified
  - Maybe also provide a default locale and timezone for the same reason?
  - Is there a way to re-use the active project ID from `gcloud` (or other metadata from `gcloud`) to avoid specifying those arguments at all?

**Comment by xavidop** [comment]
As I said in the other issue: You are completely right, I have to specify which parameters are required and which ones are optional and add some validations. I will work on this during the upcoming weeks.

**Comment by koverholt** [comment]
> Here is the in-progress Pull Request!

Amazing! I added a `Proposed changes` section to my original post in this issue to make the proposed changes more specific and clear. And I see you are already on the case in your PR. 😄

**Comment by xavidop** [comment]
On it!

**Comment by xavidop** [comment]
Hi @koverholt this Issue is ready to review in this PR!: https://github.com/xavidop/dialogflow-cx-cli/pull/62
